spring:
  datasource:
    #driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    #url: jdbc:h2:mem:test
    url: jdbc:mysql://112.74.51.194:3306/hww?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: nihao123
    initialization-mode: always

mybatis-plus:
  global-config:
    db-config:
      id-type: id-worker
      capital-mode: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl